### ISSUE TITLE
[WIN] apsw.SQLError: SQLError: no such module: fts5

### ISSUE THREAD

**Issue by JakaKokosar** [conda-forge/apsw-feedstock#15]
Hi, when I install apsw trough conda-forge channel on windows I get a following error:

![Screenshot 2019-08-23 at 13 32 20](https://user-images.githubusercontent.com/15876321/63589932-b39c7c00-c5aa-11e9-8a26-dd49d2b0a736.png)

This however does not happen on mac or linux.

**Comment by stuertz** [comment]
Please report detailed versions. 
We may have to `--enable-fts5`

**Comment by stuertz** [comment]
I can reproduce it:
```
> python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32

Type "help", "copyright", "credits" or "license" for more information.
>>> import apsw
>>> c=apsw.Connection(":memory:")
>>> cursor=c.cursor()
>>> cursor.execute("CREATE VIRTUAL TABLE testing USING fts5(data);")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\bld\apsw_1564961493204\work\src\cursor.c", line 236, in resetcursor
apsw.SQLError: SQLError: no such module: fts5

>conda info

     active environment : None
       user config file : c:\users\js\Documents\.condarc
 populated config files : c:\users\js\Documents\.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages :
       base environment : C:\Users\js\AppData\Local\Continuum\miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\js\AppData\Local\Continuum\miniconda2\pkgs
                          c:\users\js\Documents\.conda\pkgs
                          C:\Users\js\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\js\AppData\Local\Continuum\miniconda2\envs
                          c:\users\js\Documents\.conda\envs
                          C:\Users\js\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/2.7.16 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


>conda list
# packages in environment at C:\Users\js\AppData\Local\Continuum\miniconda2:
#
# Name                    Version                   Build  Channel
apsw                      3.28.0.r1        py27h9dc6b9e_0    conda-forge
asn1crypto                0.24.0                   py27_0
astroid                   1.6.5                    py27_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                        py_2
bzip2                     1.0.6                h0c8e037_5
ca-certificates           2019.5.15                     1
certifi                   2019.6.16                py27_1
cffi                      1.12.3           py27hcfb25f9_0
chardet                   3.0.4                 py27_1003
colorama                  0.4.1                    py27_0
conda                     4.7.11                   py27_0
conda-package-handling    1.3.11                   py27_0
configparser              3.7.4                    py27_0
cryptography              2.7              py27hcfb25f9_0
entrypoints               0.3                      py27_0
enum34                    1.1.6                    py27_1
flake8                    3.7.7                    py27_0
functools32               3.2.3.2                  py27_1
futures                   3.3.0                    py27_0
idna                      2.8                      py27_0
ipaddress                 1.0.22                   py27_0
isort                     4.3.21                   py27_0
lazy-object-proxy         1.4.1            py27h0c8e037_0
libarchive                3.3.3                h891e933_5
libiconv                  1.15                 hda2e4ec_7
libxml2                   2.9.9                h325896a_0
lz4-c                     1.8.1.2              h3cc03e0_0
lzo                       2.10                 h0bb7fe3_2
mccabe                    0.6.1                    py27_1
menuinst                  1.4.16           py27h0c8e037_0
openssl                   1.1.1c               h0c8e037_1
pip                       19.2.2                   py27_0
pycodestyle               2.5.0                    py27_0
pycosat                   0.6.3            py27h0c8e037_0
pycparser                 2.19                     py27_0
pyflakes                  2.1.1                    py27_0
pylint                    1.9.2                    py27_0
pyopenssl                 19.0.0                   py27_0
pysocks                   1.7.0                    py27_0
python                    2.7.16               hcb6e200_0
python-libarchive-c       2.8                     py27_13
pywin32                   223              py27h0c8e037_1
requests                  2.22.0                   py27_0
ruamel_yaml               0.15.46          py27h0c8e037_0
setuptools                41.0.1                   py27_0
singledispatch            3.4.0.3          py27h3f9d112_0
six                       1.12.0                   py27_0
sqlite                    3.29.0               h0c8e037_0
tqdm                      4.32.1                     py_0
typing                    3.7.4                    py27_0
urllib3                   1.24.2                   py27_0
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wheel                     0.33.4                   py27_0
win_inet_pton             1.1.0                    py27_0
wincertstore              0.2              py27hf04cefb_0
wrapt                     1.11.2           py27h0c8e037_0
xz                        5.2.4                h3cc03e0_4
yaml                      0.1.7                h3e6d941_2
zlib                      1.2.11               h3cc03e0_3
zstd                      1.3.7                h1b0e4d7_0
```

**Comment by JakaKokosar** [comment]
```
     active environment : aspw
    active env location : C:\Users\jakakokosar\Miniconda3\envs\aspw
            shell level : 2
       user config file : C:\Users\jakakokosar\.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Users\jakakokosar\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\jakakokosar\Miniconda3\pkgs
                          C:\Users\jakakokosar\.conda\pkgs
                          C:\Users\jakakokosar\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jakakokosar\Miniconda3\envs
                          C:\Users\jakakokosar\.conda\envs
                          C:\Users\jakakokosar\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

```

**Comment by stuertz** [comment]
This is not a bug of the apsw package, but of the official conda sqlite build:
```
Library\bin\sqlite3.exe
SQLite version 3.29.0 2019-07-10 17:32:03
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE VIRTUAL TABLE testing USING fts5(data);
Error: no such module: fts5
sqlite>
```
Please file an issue over there. 

As a workaround get sqlite3 package from conda-forge. That sqlite package supports fts5.
See https://anaconda.org/conda-forge/sqlite for details.
