### ISSUE TITLE
[mac, py38] Test fail 'AttributeError: Can't pickle local object 'APSW.testzzForkChecker.<locals>.childtest''

### ISSUE THREAD

**Issue by stuertz** [conda-forge/apsw-feedstock#19]
Mac CI fails (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=115189&view=logs&jobId=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=0163009c-ae2d-56ec-96d8-026be7c15275)

Traceback:
```
2020-01-28T07:56:36.8037650Z running test
2020-01-28T07:56:37.1298680Z                 Python $PREFIX/bin/python sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)
2020-01-28T07:56:37.1300070Z Testing with APSW file $PREFIX/lib/python3.8/site-packages/apsw.cpython-38-darwin.so
2020-01-28T07:56:37.1300920Z           APSW version 3.30.1-r1
2020-01-28T07:56:37.1301260Z     SQLite lib version 3.30.1
2020-01-28T07:56:37.1301480Z SQLite headers version 3030001
2020-01-28T07:56:37.1301670Z     Using amalgamation False
2020-01-28T07:59:01.9292750Z ......................................................................................E
2020-01-28T07:59:01.9294330Z ======================================================================
2020-01-28T07:59:01.9296630Z ERROR: testzzForkChecker (tests.APSW)
2020-01-28T07:59:01.9297570Z Test detection of using objects across fork
2020-01-28T07:59:01.9300220Z ----------------------------------------------------------------------
2020-01-28T07:59:01.9301260Z Traceback (most recent call last):
2020-01-28T07:59:01.9303420Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/work/tests.py", line 8487, in testzzForkChecker
2020-01-28T07:59:01.9304360Z     p.start()
2020-01-28T07:59:01.9306770Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/process.py", line 121, in start
2020-01-28T07:59:01.9307890Z     self._popen = self._Popen(self)
2020-01-28T07:59:01.9310450Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
2020-01-28T07:59:01.9311500Z     return _default_context.get_context().Process._Popen(process_obj)
2020-01-28T07:59:01.9314920Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
2020-01-28T07:59:01.9315920Z     return Popen(process_obj)
2020-01-28T07:59:01.9318450Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
2020-01-28T07:59:01.9319500Z     super().__init__(process_obj)
2020-01-28T07:59:01.9322100Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
2020-01-28T07:59:01.9323170Z     self._launch(process_obj)
2020-01-28T07:59:01.9325720Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
2020-01-28T07:59:01.9326770Z     reduction.dump(process_obj, fp)
2020-01-28T07:59:01.9329500Z   File "/usr/local/miniconda/conda-bld/apsw_1580198052649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
2020-01-28T07:59:01.9330470Z     ForkingPickler(file, protocol).dump(obj)
2020-01-28T07:59:01.9331330Z AttributeError: Can't pickle local object 'APSW.testzzForkChecker.<locals>.childtest'
2020-01-28T07:59:01.9331570Z 
2020-01-28T07:59:01.9332460Z ----------------------------------------------------------------------
2020-01-28T07:59:01.9332930Z Ran 87 tests in 144.768s
```

Looks similar to: https://github.com/rogerbinns/apsw/issues/277
 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/js/miniconda2/envs/py38build:
#
# Name                    Version                   Build  Channel
apsw                      3.30.1.post1             pypi_0    pypi
beautifulsoup4            4.8.2                    py38_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38h33e799b_0    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
conda                     4.8.2                    py38_0    conda-forge
conda-build               3.18.11                  py38_0    conda-forge
conda-forge-pinning       2020.01.27                    0    conda-forge
conda-package-handling    1.6.0            py38h0b31af3_1    conda-forge
conda-smithy              3.6.6                      py_0    conda-forge
cryptography              2.8              py38hafa8578_1    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
deprecated                1.2.7                      py_0    conda-forge
expat                     2.2.9                h4a8c4bd_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
git                       2.24.0          pl526hdc91d69_1    conda-forge
gitdb2                    2.0.6                      py_0    conda-forge
gitpython                 3.0.5                      py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py38_1000    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libarchive                3.3.3             h8912c15_1007    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblief                   0.9.0                h3e78482_1    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py38h0b31af3_0    conda-forge
msrest                    0.6.10                     py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
pcre                      8.43                 h4a8c4bd_0    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pip                       20.0.2                   py38_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.7            py38h0b31af3_0    conda-forge
py-lief                   0.9.0            py38h0ceac7d_1    conda-forge
pycosat                   0.6.3           py38h0b31af3_1002    conda-forge
pycparser                 2.19                     py38_1    conda-forge
pycrypto                  2.6.1           py38h0b31af3_1003    conda-forge
pygithub                  1.43.6                   py38_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                h5c2c468_1    conda-forge
python-libarchive-c       2.9                      py38_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py38h0b31af3_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py38_1    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
ripgrep                   11.0.2               h01d97ff_3    conda-forge
ruamel.yaml               0.16.6           py38h0b31af3_0    conda-forge
ruamel.yaml.clib          0.2.0            py38h0b31af3_0    conda-forge
ruamel_yaml               0.15.80         py38h0b31af3_1000    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
six                       1.14.0                   py38_0    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
soupsieve                 1.9.4                    py38_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tqdm                      4.42.0                     py_0    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.34.1                   py38_0    conda-forge
wrapt                     1.11.2           py38h0b31af3_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py38build
    active env location : /Users/js/miniconda2/envs/py38build
            shell level : 2
       user config file : /Users/js/.condarc
 populated config files : /Users/js/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __osx=10.15.2
       base environment : /Users/js/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/js/miniconda2/pkgs
                          /Users/js/.conda/pkgs
       envs directories : /Users/js/miniconda2/envs
                          /Users/js/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/2.7.15 Darwin/19.2.0 OSX/10.15.2
                UID:GID : 502:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by stuertz** [comment]
fixed with v3.33.1 #23
